"""add recipe table

Revision ID: 867f41206258
Revises: 
Create Date: 2024-03-22 01:30:06.368323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import DateTime


# revision identifiers, used by Alembic.
revision: str = '867f41206258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('cuisine', sa.Enum('world', 'italian', 'american', 'thai', 'japanese', name='cuisinetype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', DateTime(), nullable=True),
    sa.Column('modified_at', DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
